# Generated by Django 5.2 on 2025-05-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(),
        ),
    ]
