# Generated by Django 5.2.1 on 2025-05-31 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_note_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soal', models.TextField(max_length=250)),
                ('correct_answer', models.CharField(max_length=250)),
                ('option_a', models.CharField(max_length=250)),
                ('option_b', models.CharField(max_length=250)),
                ('option_c', models.CharField(max_length=250)),
                ('option_d', models.CharField(max_length=250)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.note')),
            ],
        ),
    ]
