# Generated by Django 5.2.1 on 2025-06-08 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_examsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='note',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='learning.note'),
        ),
    ]
