# Generated by Django 5.2.1 on 2025-06-08 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_examsession_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.note'),
        ),
    ]
