# Generated by Django 5.2.1 on 2025-06-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_alter_examsession_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examanswer',
            old_name='exam',
            new_name='note',
        ),
    ]
